### ISSUE TITLE
No Items 

### ISSUE THREAD

**Issue by Voriodon** [BEEmod/BEE2.2#3]
I installed BEE2 today, and the only things that work are Styles and Palette Layouts. There are no items displayed in the main area. I don't know if I installed it wrong, or a wrong version? I have BEE2 2.2.5. (WIN7) I have my portal 2 destination set right so it launches correctly, been having this problem for awhile, and tried to fix it myself and failed.
![capture](https://cloud.githubusercontent.com/assets/14636504/16629621/0740a0ca-437c-11e6-8408-055afdb2ee05.JPG)

**Comment by SpyyZ158** [comment]
I had this problem too then I told myself to just remove it

**Comment by BenVlodgi** [comment]
This happens in the BEE2.2.5 when your portal 2 is not on the C Drive.
Fixed in [BEE2.4.x](https://github.com/BenVlodgi/BEE2.4/releases)
