### ISSUE TITLE
Missing Styles/Items

### ISSUE THREAD

**Issue by ChristopherFredC** [BEEmod/BEE2.2#4]
I had BEE2 not too long ago, but I delteded it and when I reinstalled it, several items and styles were missing and still are. There are no co-op checkpoints, overgrown styles, and other things like that missing.

UPDATE

After installing the addons, for some reason they all returned. I know that I never had the addons in the past, though.

**Comment by vrad-exe** [comment]
You must have had the addons before. Both of the features you mentioned are part of the addons, and wouldn't have appeared without them. Where did you download it from originally?

**Comment by vrad-exe** [comment]
You should be using [BEE2.4](https://github.com/BEEmod/BEE2.4) anyway.
